package com.chris.tictactoe.rest.dao;

import java.util.HashMap;
import java.util.Map;

import com.chris.tictactoe.rest.model.Game;

public class GameStaticRepository extends StaticRepository<Game> {
	private final static Map<String, Game> REPOSITORY = new HashMap<String, Game>();
	
	private static GameStaticRepository gameStaticRepository;
	
	private static int idGenerator = 0;
	
	public GameStaticRepository(Map<String, Game> staticRepo) {
		super(staticRepo);
	}
	
	@Override
	public String save(Game entity) {
		idGenerator++;
		super.save(String.valueOf(idGenerator), entity);
		
		return String.valueOf(idGenerator);
	}
	
	@Override
	public void save(String id, Game entity) {
		throw new UnsupportedOperationException("The ID is autogenerated. Please use instead save(entity) method.");
	}
	
	public static GameStaticRepository getInstance(){
		if(gameStaticRepository == null){
			gameStaticRepository = new GameStaticRepository(REPOSITORY);
		}
		
		return gameStaticRepository;
	}
	

}
